routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix'=>'auth','namespace'=>'Authentication'],function () {
    Route::get('login','AuthenticationController@index')->name('login');
    Route::post('admin/login','AuthenticationController@userLogin')->name('admin.login');
});

Route::group(['prefix'=>'admin','middleware'=>'auth','namespace'=>'Dashboard'],function () {
    Route::get('dashboard','DashboardController@index')->name('dashboard');
    Route::get('notifications','DashboardController@suggestionsCount')->name('notifications.count');
    Route::get('requests','DashboardController@requestsCount')->name('requests.count');
    Route::post('logout', 'DashboardController@logout')->name('logout');

     Route::prefix('profile')->group(function (){
         Route::get('','ProfileController@index')->name('profile.index');
         Route::post('/update/{id}','ProfileController@update')->name('profile.update');
     });

    Route::prefix('settings')->group(function (){
        Route::get('','SettingsController@index')->name('settings.index');
        Route::post('/update','SettingsController@update')->name('settings.update');
    });
    Route::prefix('suggestion')->group(function (){
        Route::get('','SuggestionsController@index')->name('suggestion.index');
        Route::get('/unread','SuggestionsController@unreadMsg')->name('suggestion.unread');
        Route::get('/requests','SuggestionsController@unActiveRequests')->name('requests.unread');
        Route::get('/show/{id}','SuggestionsController@show')->name('suggestion.show');
        Route::post('/{id}','SuggestionsController@destroy')->name('suggestion.destroy');
    });
    Route::prefix('privacy')->group(function (){
        Route::get('','PrivacyController@index')->name('privacy.index');
        Route::post('/update','PrivacyController@update')->name('privacy.update');
    });
//    Route::resource('slider', 'SlidersController');
    Route::prefix('slider')->group(function (){
        Route::get('','SlidersController@index')->name('slider.index');
        Route::get('/create','SlidersController@create')->name('slider.create');
        Route::post('/store','SlidersController@store')->name('slider.store');
        Route::post('/{id}','SlidersController@destroy')->name('slider.destroy');
        Route::post('/update/{id}','SlidersController@update')->name('slider.update');
        Route::get('/edit/{id}','SlidersController@edit')->name('slider.edit');
    });

    Route::prefix('station')->group(function (){
        Route::get('','StationsController@index')->name('station.index');
        Route::get('/create','StationsController@create')->name('station.create');
        Route::post('/store','StationsController@store')->name('station.store');
        Route::post('/{id}','StationsController@destroy')->name('station.destroy');
        Route::post('/update/{id}','StationsController@update')->name('station.update');
        Route::get('/edit/{id}','StationsController@edit')->name('station.edit');
        Route::get('/{id}','StationsController@printQr')->name('station.qr.print');
    });

    Route::prefix('charity')->group(function (){
        Route::get('','CharitiesController@index')->name('charity.index');
        Route::get('/create','CharitiesController@create')->name('charity.create');
        Route::post('/store','CharitiesController@store')->name('charity.store');
        Route::post('/{id}','CharitiesController@destroy')->name('charity.destroy');
        Route::post('/update/{id}','CharitiesController@update')->name('charity.update');
        Route::get('/edit/{id}','CharitiesController@edit')->name('charity.edit');
    });

    Route::prefix('payments')->group(function (){
        Route::get('','PaymentsController@index')->name('payments.index');
        Route::get('/{id}','PaymentsController@show')->name('payments.show');
        Route::post('/{id}','PaymentsController@destroy')->name('payments.destroy');
        Route::get('/invoice/{id}','PaymentsController@generatePdf')->name('payments.invoice.show');
    });

    Route::prefix('user/admin')->group(function (){
        Route::get('','AdminsController@index')->name('admin.index');
        Route::get('/create','AdminsController@create')->name('admin.create');
        Route::post('/store','AdminsController@store')->name('admin.store');
        Route::get('/edit/{id}','AdminsController@edit')->name('admin.edit');
        Route::post('/update/{id}','AdminsController@update')->name('admin.update');
        Route::post('/{id}','AdminsController@destroy')->name('admin.destroy');
    });

    Route::prefix('user/user')->group(function (){
        Route::get('','UsersController@index')->name('user.index');
        Route::get('/create','UsersController@create')->name('user.create');
        Route::post('/store','UsersController@store')->name('user.store');
        Route::get('/edit/{id}','UsersController@edit')->name('user.edit');
        Route::post('/update/{id}','UsersController@update')->name('user.update');
        Route::post('/{id}','UsersController@destroy')->name('user.destroy');
    });

    Route::prefix('user/moderator')->group(function (){
        Route::get('','ModeratorsController@index')->name('moderator.index');
        Route::get('/create','ModeratorsController@create')->name('moderator.create');
        Route::post('/store','ModeratorsController@store')->name('moderator.store');
        Route::get('/edit/{id}','ModeratorsController@edit')->name('moderator.edit');
        Route::post('/update/{id}','ModeratorsController@update')->name('moderator.update');
        Route::post('/{id}','ModeratorsController@destroy')->name('moderator.destroy');
    });

    Route::prefix('notification')->group(function (){
        Route::get('','NotificationsController@index')->name('notification.index');
        Route::get('/create','NotificationsController@create')->name('notification.create');
        Route::post('/store','NotificationsController@store')->name('notification.store');
    });
});

app/Suggestion.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Suggestion extends Model
{
    protected $table='suggestions';
    protected $fillable=[ 'user_id','email', 'suggestion','view'];

    public function user()
    {
        return $this->belongsTo('App\User','user_id');
    }

    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->toDateString();
    }
}

resources/views/dashboard/views/suggestions/index.blade.php
@extends('dashboard.layouts.master')
@section('content')
{{--    <div class="content">--}}
{{--        <div class="container">--}}


{{--            <div class="row">--}}
{{--                <div class="col-xs-12">--}}
{{--                    <div class="page-title-box">--}}
{{--                        <h4 class="page-title">Suggestions </h4>--}}
{{--                        <ol class="breadcrumb p-0 m-0">--}}
{{--                            <li>--}}
{{--                                <a href="{{route('dashboard')}}">Nift</a>--}}
{{--                            </li>--}}
{{--                            <li class="active">--}}
{{--                                Suggestions--}}
{{--                            </li>--}}
{{--                        </ol>--}}
{{--                        <div class="clearfix"></div>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--            <!-- end row -->--}}


{{--            <div class="row">--}}
{{--                <div class="col-sm-12">--}}
{{--                    <div class="card-box table-responsive">--}}
{{--                        <h4 class="m-t-0 header-title"><b>Suggestions Table</b></h4>--}}

{{--                        <table id="datatable" class="table table-striped table-bordered">--}}
{{--                            <thead>--}}
{{--                            <tr>--}}
{{--                                <th>#</th>--}}
{{--                                <th>Name</th>--}}
{{--                                <th>email</th>--}}
{{--                                <th>suggestion</th>--}}
{{--                                <th>Created At</th>--}}
{{--                                <th>Actions</th>--}}
{{--                            </tr>--}}
{{--                            </thead>--}}


{{--                            <tbody>--}}
{{--                            @foreach($suggestions as $key=>$suggestion)--}}
{{--                            <tr>--}}
{{--                                <td>{{ $key + 1 }}</td>--}}
{{--                                <td>{{$suggestion->user->name}}</td>--}}
{{--                                <td>{{$suggestion->email}}</td>--}}
{{--                                <td>{{$suggestion->suggestion}}</td>--}}
{{--                                <td>{{$suggestion->created_at}}</td>--}}
{{--                                <td>--}}
{{--                                    <a href="{{ route('suggestion.show',$suggestion->id) }}" class="btn btn-info active"><i class="material-icons"><i class="mdi mdi-eye"></i></i></a>--}}

{{--                                    <form id="delete-form-{{ $suggestion->id }}" action="{{ route('suggestion.destroy',$suggestion->id) }}" style="display: none;" method="POST">--}}
{{--                                        @csrf--}}
{{--                                    </form>--}}
{{--                                    <button type="button" class="btn btn-danger active" onclick="if(confirm('Are you sure? You want to delete this?')){--}}
{{--                                            event.preventDefault();--}}
{{--                                            document.getElementById('delete-form-{{ $suggestion->id }}').submit();--}}
{{--                                            }else {--}}
{{--                                            event.preventDefault();--}}
{{--                                            }"><i class="material-icons"><i class="mdi mdi-delete"></i></i></button>--}}
{{--                                </td>--}}
{{--                            </tr>--}}
{{--                            @endforeach--}}


{{--                            </tbody>--}}
{{--                        </table>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}





{{--        </div> <!-- container -->--}}
{{--    </div>--}}


<div class="page-body">
    <div class="container-fluid">
        <div class="page-header">
            <div class="row">
                <div class="col">
                    <div class="page-header-left">
                        <h3>{{trans('suggestion.suggestionsTable')}}</h3>
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i data-feather="home"></i></a></li>
                            <li class="breadcrumb-item">{{trans('suggestion.suggestions')}}</li>
                            <li class="breadcrumb-item">{{trans('dashboard.nift')}}</li>
                            <li class="breadcrumb-item active">{{trans('suggestion.suggestions')}}</li>
                        </ol>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <!-- Container-fluid starts-->
    <div class="container-fluid">
        <div class="row">
            <!-- Zero Configuration  Starts-->
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5> {{trans('suggestion.suggestionsTable')}} </h5>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="display" id="basic-1">
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>{{trans('suggestion.Name')}}</th>
                                    <th>{{trans('suggestion.email')}}</th>
                                    <th>{{trans('suggestion.suggestion')}}</th>
                                    <th>{{trans('suggestion.CreatedAt')}}</th>
                                    <th>{{trans('suggestion.actions')}}</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($suggestions as $key=>$suggestion)
                                    <tr>
                                        <td>{{ $key + 1 }}</td>
                                        <td>{{$suggestion->user->name}}</td>
                                        <td>{{$suggestion->email}}</td>
                                        <td>{{$suggestion->suggestion}}</td>
                                        <td>{{$suggestion->created_at}}</td>
                                        <td>
                                            <a href="{{ route('suggestion.show',$suggestion->id) }}" class="btn btn-info">{{trans('admin.details')}}</a>

                                            <form id="delete-form-{{ $suggestion->id }}" action="{{ route('suggestion.destroy',$suggestion->id) }}" style="display: none;" method="POST">
                                                @csrf
                                            </form>
                                            <button type="button" class="btn btn-danger" onclick="if(confirm('{{trans('admin.deletemsg')}}')){
                                                    event.preventDefault();
                                                    document.getElementById('delete-form-{{ $suggestion->id }}').submit();
                                                    }else {
                                                    event.preventDefault();
                                                    }">{{trans('admin.delete')}}</button>
                                        </td>
                                    </tr>
                                @endforeach


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Zero Configuration  Ends-->

        </div>
    </div>
    <!-- Container-fluid Ends-->
</div>




@endsection

resources/views/dashboard/views/suggestions/show.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-header">
                <div class="row">
                    <div class="col">
                        <div class="page-header-left">
                            <h3>{{trans('suggestion.read')}}</h3>
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i data-feather="home"></i></a></li>
                                <li class="breadcrumb-item">{{trans('suggestion.suggestions')}} </li>
                                <li class="breadcrumb-item active"> {{trans('suggestion.read')}}</li>
                            </ol>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        <div class="container-fluid">
            <div class="email-wrap">
                <div class="row">


                    <div class="col-xl-12 col-md-12">
                        <div class="email-right-aside">
                            <div class="card email-body radius-left">
                                <div class="pl-0">
                                    <div class="tab-content">
                                        <div class="tab-pane fade" id="pills-darkhome" role="tabpanel" aria-labelledby="pills-darkhome-tab">
                                            <div class="email-compose">
                                                <div class="email-top compose-border">
                                                    <div class="row">
                                                        <div class="col-sm-8 xl-50">
                                                            <h4 class="mb-0">New Message</h4>
                                                        </div>
                                                        <div class="col-sm-4 btn-middle xl-50">
                                                            <button class="btn btn-primary btn-block btn-mail text-center mb-0 mt-0" type="button"><i class="fa fa-paper-plane mr-2"></i> SEND</button>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="email-wrapper">
                                                    <form class="theme-form">
                                                        <div class="form-group">
                                                            <label class="col-form-label pt-0" for="exampleInputEmail1">To</label>
                                                            <input class="form-control" id="exampleInputEmail1" type="email">
                                                        </div>
                                                        <div class="form-group">
                                                            <label for="exampleInputPassword1">Subject</label>
                                                            <input class="form-control" id="exampleInputPassword1" type="text">
                                                        </div>
                                                        <div class="form-group mb-0">
                                                            <label class="text-muted">Message</label>
                                                            <textarea id="text-box" name="text-box" cols="10" rows="2">                                                            </textarea>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="tab-pane fade active show" id="pills-darkprofile" role="tabpanel" aria-labelledby="pills-darkprofile-tab">
                                            <div class="email-content">
                                                <div class="email-top">
                                                    <div class="row">
                                                        <div class="col-md-6 xl-100 col-sm-12">
                                                            <div class="media"><img class="mr-3 rounded-circle" src="../assets/images/user/user.png" alt="">
                                                                <div class="media-body">
                                                                    <h6>
                                                                        <img alt="" width="100px" src="{{$suggestion->user->image}}" class="media-object thumb-sm img-circle">
                                                                        <br>
                                                                        <small><span class="digits">{{$suggestion->user->name}} <span class="digits">
                                                                                    <br> {{$suggestion->created_at}}</span></span></small></h6>
                                                                    <p>{{$suggestion->user->email}}</p>
                                                                </div>
                                                            </div>
                                                        </div>

                                                    </div>
                                                </div>
                                                <div class="email-wrapper">
                                                    <p>{{$suggestion->suggestion}}</p>




                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Container-fluid Ends-->
    </div>











{{--<div class="content">--}}
{{--    <div class="container">--}}


{{--        <div class="row">--}}
{{--            <div class="col-xs-12">--}}
{{--                <div class="page-title-box">--}}
{{--                    <h4 class="page-title">Suggestion Read </h4>--}}
{{--                    <ol class="breadcrumb p-0 m-0">--}}
{{--                        <li>--}}
{{--                            <a href="{{route('dashboard')}}">Nift</a>--}}
{{--                        </li>--}}
{{--                        <li>--}}
{{--                            <a href="{{route('suggestion.index')}}">Suggestion </a>--}}
{{--                        </li>--}}
{{--                        <li class="active">--}}
{{--                            Suggestion Read--}}
{{--                        </li>--}}
{{--                    </ol>--}}
{{--                    <div class="clearfix"></div>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--        <!-- end row -->--}}


{{--        <div class="row">--}}
{{--            <div class="col-xs-12">--}}
{{--                <div class="mails">--}}

{{--                    <div class="table-box">--}}

{{--                        <div class="table-detail mail-right">--}}



{{--                            <div class="row">--}}
{{--                                <div class="col-sm-12">--}}
{{--                                    <div class="card-box m-t-20">--}}


{{--                                        <div class="media m-b-30 ">--}}
{{--                                            <a href="#" class="pull-left">--}}
{{--                                                <img alt="" src="{{$suggestion->user->image}}" class="media-object thumb-sm img-circle">--}}
{{--                                            </a>--}}
{{--                                            <div class="media-body">--}}
{{--                                                <span class="media-meta pull-right">{{$suggestion->created_at}}</span>--}}
{{--                                                <h4 class="text-primary m-0">{{$suggestion->user->name}}</h4>--}}
{{--                                                <small class="text-muted">From: {{$suggestion->email}}</small>--}}
{{--                                            </div>--}}
{{--                                        </div> <!-- media -->--}}


{{--                                        <p>{{$suggestion->suggestion}}</p>--}}

{{--                                        <hr/>--}}


{{--                                    </div>--}}
{{--                                    <!-- card-box -->--}}
{{--                                </div> <!-- end col -->--}}
{{--                            </div> <!-- end row -->--}}

{{--                            <div class="row">--}}
{{--                                <div class="col-sm-12">--}}
{{--                                    <div class="text-right">--}}
{{--                                        <a href="{{route('suggestion.index')}}" type="button" class="btn btn-primary waves-effect waves-light w-md m-b-30"><i class="mdi mdi-reply m-r-10"></i>Back</a>--}}
{{--                                    </div>--}}
{{--                                </div>--}}
{{--                            </div>--}}

{{--                            <!-- End row -->--}}

{{--                        </div> <!-- table detail -->--}}
{{--                    </div>--}}
{{--                    <!-- end table box -->--}}

{{--                </div> <!-- mails -->--}}
{{--            </div>--}}
{{--        </div>--}}
{{--        <!-- end row -->--}}

{{--    </div> <!-- container -->--}}
{{--</div>--}}
@endsection